### ISSUE TITLE
HomeScreen에서 보여지는 Grid 크기가 다릅니다.

### ISSUE THREAD

**Issue by Hyeonseo4799** [Team-GBS/GBS-Android#27]
## 좌측 아이템이 우측보다 조금 더 큰 모습
![Screenshot_1680766095](https://user-images.githubusercontent.com/85855341/230306901-2f386cb4-07c9-4cac-ac4f-b51b9ab74082.png)

**Comment by ImGaram** [comment]
고치겠습니다.
